workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        APP_ID: "com.agroseguro.chatdocumental"
        XCODE_PROJECT: "ios/App.xcodeproj"
        XCODE_SCHEME: "App"
    scripts:
      - name: Instalar dependencias y compilar la app
        script: |
          npm install
          npm run build  # Agregar este paso para generar la carpeta www
          npx cap sync ios
          cd ios && pod install && cd ..
      - name: Construir la app
        script: |
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -sdk iphoneos -configuration Release build
