workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        APP_ID: "com.agroseguro.chatdocumental"
        XCODE_PROJECT: "ios/App/App.xcodeproj"  # ⚠️ Corrige la ruta al proyecto Xcode
        XCODE_SCHEME: "App"
    scripts:
      - name: Debug - Verificar directorios antes de instalar dependencias
        script: |
          pwd
          ls -la
          ls -la ios
          ls -la ios/App
      - name: Instalar dependencias y compilar la app
        script: |
          npm install
          npm run build  # Generar la carpeta www
          npx cap sync ios
          cd ios/App  # ⚠️ Cambia a la carpeta correcta donde está el Podfile
          pod install
          cd ../..
      - name: Construir la app
        script: |
          xcodebuild -workspace "ios/App/App.xcworkspace" -scheme "$XCODE_SCHEME" -sdk iphoneos -configuration Release build
