workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        APP_ID: "com.miapp.id"  # Reemplaza con tu ID de app real
        XCODE_PROJECT: "ios/App.xcodeproj"
        XCODE_SCHEME: "App"
    scripts:
      - name: Instalar dependencias
        script: |
          npm install
          npx cap sync ios
          cd ios && pod install && cd ..
      - name: Construir la app
        script: |
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -sdk iphoneos -configuration Release build
